export const icons = {
  email: require('../../assets/icons/email.png'),
  password: require('../../assets/icons/password.png'),
  google: require('../../assets/icons/google.png'),
  user: require('../../assets/icons/user.png'),
  phone: require('../../assets/icons/phone.png'),
  lock: require('../../assets/icons/lock.png'),
  downArrow: require('../../assets/icons/downArrow.png'),
  attach: require('../../assets/icons/frame.png'),
  camera: require('../../assets/icons/camera.png'),
  gallery: require('../../assets/icons/gallery.png'),
  pdf: require('../../assets/icons/pdf.png'),
  down: require('../../assets/icons/down.png'),
  career: require('../../assets/icons/jobPage.png'),
  eyeClose: require('../../assets/icons/eyeClose.png'),
  eyeOpen: require('../../assets/icons/eyeOpen.png'),
  home: require('../../assets/icons/home.png'),
  right: require('../../assets/icons/right.png'),
  plus: require('../../assets/icons/plus.png'),
  left: require('../../assets/icons/left.png'),
};
